name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install Dependencies
      run: |
        npm install         # Install regular dependencies
        npm install --save-dev jest
        npm install --save-dev @testing-library/jest-dom
        # Add other testing dependencies if needed
  

    - name: Run Tests
      run: npm test

    - name: Install Webpack
      run: npm install webpack webpack-cli --save-dev

    - name: Build with Webpack
      run: npx webpack

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1
        with:
          command: 'deploy'
          args: '--prod'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    